### ISSUE TITLE
Improve exception handling and error message in case no driver is found when using the SpecFlow plugin

### ISSUE THREAD

**Issue by SabotageAndi** [testproject-io/csharp-opensdk#105]
I tried the SpecFlow plugin with a project that doesn't use Selenium for automation to get the reporting capabilities. This was not possible, as I get the following exception:

```
Message: 
    TestProject.OpenSDK.Internal.Exceptions.AgentConnectException : No active Agent development session found. Please ensure that driver.Quit() is called in an [After] method, not in a step definition method.
  Stack Trace: 
    TestProjectPlugin.RuntimePluginTestExecutionLifecycleEvents_AfterStep(Object sender, RuntimePluginAfterStepEventArgs eventArgs)
    RuntimePluginTestExecutionLifecycleEvents.RaiseAfterStep(IObjectContainer objectContainer)
    RuntimePluginTestExecutionLifecycleEventEmitter.RasiseExecutionLifecycleEvent(HookType hookType, IObjectContainer container)
    TestExecutionEngine.FireScenarioEvents(HookType bindingEvent)
    TestExecutionEngine.OnStepEnd()
    TestExecutionEngine.ExecuteStep(IContextManager contextManager, StepInstance stepInstance)
    TestExecutionEngine.Step(StepDefinitionKeyword stepDefinitionKeyword, String keyword, String text, String multilineTextArg, Table tableArg)
    TestRunner.Given(String text, String multilineTextArg, Table tableArg, String keyword)
    CalculatorFeature.AddTwoNumbers() line 10
```

I had a look in the code and found the check at https://github.com/testproject-io/csharp-opensdk/blob/main/TestProject.OpenSDK.SpecFlowPlugin/TestProjectPlugin.cs#L70

Looks like the underlying field is only initialized when a driver was initialized.

Is this behavior on purpose?
It would limit the usability of the plugin to SpecFlow users that use Selenium. But this is only a subset of our users. They use a number of different automation libraries or none at all

**Comment by basdijkstra** [comment]
Hey @SabotageAndi, yes, this behavior is intentional. To set up a connection with the Agent (the process that takes care of all the reporting to the TestProject platform), you'll need to instantiate a TestProject driver. We don't report directly to TestProject Cloud from the test, that's all being taken care of by the Agent.

For those not using Selenium or Appium, we provide a `GenericDriver` that you can use to manually report steps and tests to TestProject. That driver should work together with the SpecFlow plugin, too, since it works just as the other (Selenium and Appium) drivers, just without actually starting a desktop or mobile browser / app session.

**Comment by SabotageAndi** [comment]
Understood, but can't be this `GenericDriver` be instantiated automatically than throwing the exception?

If that is not possible, would it be possible to throw
1. a not internal exception
2. with an exception message that instructs the user what needs to be done

For me, this looks at the moment for an internal exception and I have no idea how to fix it, except opening an issue here or in the SpecFlow repo.

**Comment by SabotageAndi** [comment]
Just tried it out. Adding a  `var client = new GenericClient()` fixed the problem.

**Comment by basdijkstra** [comment]
I'm not sure how automatically instantiating a `GenericDriver` instance would help solve the problem in a way that preserves all reporting and options for customization.

I do agree that there's room for improvement in the exception handling here, so I'll focus on that for now.

**Comment by basdijkstra** [comment]
I've just submitted #108, which addresses this issue by:

- moving all the exceptions to a namespace that does not include `Internal` (this was misleading as the exceptions are visible to the SDK users)
- adding a `NoActiveDriverFoundException` that is thrown in the situation described in this issue.

The  exception message will be `No active Agent development session found. Please ensure that you have an instance of a TestProject OpenSDK driver running. More information on how to do that can be found in the README at https://github.com/testproject-io/csharp-opensdk`.

**Comment by basdijkstra** [comment]
#108 has been merged, so this issue can be retested using the latest prerelease.

**Comment by SabotageAndi** [comment]
Looks better now!
