### ISSUE TITLE
Improve job name inferring logic in SpecFlow plugin to reflect feature name

### ISSUE THREAD

**Issue by s-glatshtein** [testproject-io/csharp-opensdk#111]
I created a simple SpecFlow feature, and noticed the job name in the report is different than the feature name.
I used the following feature, with SpecFlow.NUnit dependency:

```
Feature: My First Feature
	  My first SpecFlow feature using TestProject OpenSDK

Scenario: Login With Different Users
  Given user is on TestProject Demo Login Page
```

I implemented the `Given` step with the command `ChromeDriver driver = new ChromeDriver()`.
Checking the report, I saw the job name in the report was `MyFirstFeatureFeature`. I also saw that the generated test class had these annotations on it:
```
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("My First Feature")]
    public partial class MyFirstFeatureFeature
```

I believe we can improve the job name auto-detection by checking for this attribute on the test method's class.

**Comment by basdijkstra** [comment]
That's a great suggestion, and one that shouldn't be too hard to implement. Thanks.

**Comment by basdijkstra** [comment]
I've just submitted #114, which adds this enhancement, at least for NUnit. It works with and without SpecFlow as in both cases, the same NUnit `[Description]` attribute is used.

This feature file:

![image](https://user-images.githubusercontent.com/10740451/108854866-a2da2580-75e8-11eb-9b4e-443f365cd73a.png)

leads to this report:

![image](https://user-images.githubusercontent.com/10740451/108854789-8b02a180-75e8-11eb-8e04-4c39c4ca2d13.png)

**Comment by basdijkstra** [comment]
#114 has been merged, so this one can be retested with the latest prerelease, @s-glatshtein.

**Comment by basdijkstra** [comment]
0.66.0 is released, please retest and close this issue when you feel it's resolved: https://www.nuget.org/packages/TestProject.OpenSDK/0.66.0

**Comment by Rantzur1992** [comment]
This looks good, closing.
