### ISSUE TITLE
[Xunit] Test name is not inferred from the test method's name in TestProject reports

### ISSUE THREAD

**Issue by ArtemKuznetsovv** [testproject-io/csharp-opensdk#118]
The test name in the TestProject reports is not the same as the function name which is wrapped with the [Fact] annotation in Xunit.

The function name in code:
![image](https://user-images.githubusercontent.com/59560231/109424347-f33bf380-79eb-11eb-85a2-dd52bc01c47d.png)

The function name in the reports:
![image](https://user-images.githubusercontent.com/59560231/109424395-1c5c8400-79ec-11eb-85f8-a9162b88a087.png)

**Comment by basdijkstra** [comment]
Hey @ArtemKuznetsovv, isn't this a duplicate of #91? Could you please try again with the latest prerelease and check if that solves the problem? Thanks.

**Comment by ArtemKuznetsovv** [comment]
Hi @basdijkstra,

It is similar to #91, but now the Job and Project name are inferred correctly but the test name is not.
I also tried with the pre release version and it still didn't work.

Test name is always "Test".

**Comment by basdijkstra** [comment]
Hey @ArtemKuznetsovv, that's probably because you didn't report a test yourself (using `driver.Report().Test()`). The generic driver doesn't automatically report tests.

**Comment by vitalybu** [comment]
@basdijkstra, I think it's the second time someone raises this issue.
What is the reason for the generic driver not inferring test names?

**Comment by basdijkstra** [comment]
> @basdijkstra, I think it's the second time someone raises this issue.
> What is the reason for the generic driver not inferring test names?

I see now that this has nothing to do with the generic driver.. My bad.

There was an issue with xUnit test name inferring but that was resolved in #94. I’m curious to see if this issue is still occurring in the latest prerelease that includes that PR.

**Comment by ArtemKuznetsovv** [comment]
@basdijkstra Oh, with the latest PR it actually did work,
I guess the ticket can be closed.
