### ISSUE TITLE
SDK shows agent status code with a wrong message when a recording session is running

### ISSUE THREAD

**Issue by Rantzur1992** [testproject-io/csharp-opensdk#130]
While running a coded test using the latest pre-release build while having a recording session running returns this message:
![image](https://user-images.githubusercontent.com/6703682/110235135-2ecc4580-7f37-11eb-97a1-ee5fe0e201a6.png)

A better message should be displayed.

**Comment by vitalybu** [comment]
@Rantzur1992, that's an Agent issue as it returns a 500 status code.
Please close this issue and open an internal ticket for the Agent team.

**Comment by basdijkstra** [comment]
Closed, see @vitalybu‘s comment.
