### ISSUE TITLE
Open SDK reporting does not show failures

### ISSUE THREAD

**Issue by Chrys123** [testproject-io/csharp-opensdk#136]
Hi,
I have disabled the command reporting , so the reports show the steps only.

Now, the issue here is, that it never shows the failures like the old SDK did on the reports, even if it was failing outside the steps.

I guess that is an issue you know already, but it is really really important as I work in a big public sector organisation in the UK and these reports need to be seen by business stakeholders. 

Also, I need to do presentations and definitely I cannot present the new Open SDK reports.

**Comment by basdijkstra** [comment]
Hey @Chrys123, are you referring to the reporting of failed assertions? That's something that's not yet supported, indeed. If that's what you mean, this is registered in #59 already. We'll hopefully get to implementing that soon.

If you're referring to something different, could you please show me an example?

**Comment by Chrys123** [comment]
Im referring to assertions AND general lack of failure reporting, anything
that is failing outside the steps is not reported

**Comment by basdijkstra** [comment]
@Chrys123, can you give me an example of 'anything that is failing outside the steps'?

**Comment by Chrys123** [comment]
I think its pretty self explanatory.

Anything that I don't declare within  a report.step is not registered as
failure in the Open SDK reports.

I have discussed this already with the Test Project developers and they say
this is going to be a future feature but actually that is a major problem
for me.

**Comment by Chrys123** [comment]
Well there is no code needed I believe. I am reporting my steps inside the
reporter.step method. I disable command reports too so only the steps are
reported.

Anything that fails outside the steps is not registered as failed.

In the old SDK, it was failing even outside but only produced a message,
not a screenshot.

**Comment by basdijkstra** [comment]
And this is exactly why I think an example would be beneficial, because now I see two different kinds of potential issues you might be referring to.

1) When driver command reporting is turned off, only manually reported steps and tests will show up in the report. That means that if a WebDriver command (find element, click, send keys, get element text, etc.) fails, it will not show up in the report and will not make the report show a failed test. Potential fix: in case of a failed WebDriver command, manually report a failed step (including a screenshot) so that the error does show up in the report and the step and test are marked as failed. This is a low-impact change.

2) When the failure is *not* related to a WebDriver command (for example an assertion error occurs, or your test code throws a `NullReferenceException` or any other kind of exception), catch this error and report it manually, making the test being reported as failed. This is what #59 is supposed to do, but this is a change with much more impact.

Again: an example (a code snippet and the stack trace result from your test execution) would be very welcome, as that helps me determine what the root cause of the errors you're seeing is, and how to address them.

**Comment by Chrys123** [comment]
I  cant send you my code this is company data, its not a personal project.

There is stack trace in the command line l, where it says that the test is
failing,  but the failure is not shown in the reports. It just shows the
test as passed, while it should be failed, like the old sdk.

I am disabling driver commands. Thats all I do regarding my reporter, to
have the steps reported. I dont care about reporting the driver commands.

this.reporter.DisableCommandReports(true);

**Comment by basdijkstra** [comment]
I appreciate you can't send the code, but I need at least a stack trace to see where the exception originates from.. If you're uncomfortable pasting this on a public GitHub repository feel free to email it to bas@ontestautomation.com.

**Comment by Chrys123** [comment]
I will paste the stack trace but it's an normal no such element found
exception which results in failure. This for example is not registered in
the reports.  I will paste the stack trace shortly.

**Comment by basdijkstra** [comment]
Thank you. A 'no such element' exception is actually something that could be solved by the first (and easier) option, because it is a direct result of a WebDriver command. I'm happy to implement that right away.

**Comment by basdijkstra** [comment]
So, I've made a small change that now always reports failing WebDriver commands, even if command reports are disabled. Still thinking about whether or not to make this configurable, but given the following test:

```csharp
[TestInitialize]
public void StartBrowser()
{
    this.driver = new ChromeDriver();
    this.driver.Report().DisableCommandReports(true);
}

[TestMethod]
public void ThisIsAFeatureTest()
{
    this.driver.Navigate().GoToUrl("https://example.testproject.io");
    this.driver.FindElement(By.CssSelector("#name")).SendKeys("John Smith");
    this.driver.FindElement(By.CssSelector("#password")).SendKeys("12345");
    this.driver.Report().Step(description: "Just a passing step", passed: true);

    // this command fails
    this.driver.FindElement(By.CssSelector("#doesnotexist")).Click();

    Assert.IsTrue(this.driver.FindElement(By.CssSelector("#greetings")).Displayed);
}
```

produces the following report:

![image](https://user-images.githubusercontent.com/10740451/111614153-8db77780-87df-11eb-9cd4-945b0c0e806d.png)

As you can see, passed driver commands are not reported, manually reported steps are reported, but the failing driver command is reported, too, including a screenshot.

Is that a solution that would be helpful in your situation, @Chrys123?

**Comment by Chrys123** [comment]
System.ArgumentException : elementDictionary
Parameter name: The specified dictionary does not contain an element
reference
  Stack Trace:
     at
OpenQA.Selenium.Remote.RemoteWebElementFactory.GetElementId(Dictionary`2
elementDictionary)
   at
OpenQA.Selenium.Remote.RemoteWebElementFactory.CreateElement(Dictionary`2
elementDictionary)
   at
OpenQA.Selenium.Remote.RemoteWebDriver.GetElementFromResponse(Response
response)
   at
TestProject.SDK.Examples.Web.Test.Pages.CommonElementsPage.clickNextButton()
in C:\Users\ChrysanthiT\Desktop\NMC -
Copy\NMC_Online_Automation_Project\NMC_Online_Automation_Project\Web\Test\TestProject.SDK.Examples.Web.Test\Test\RevalidationTests\Pages\CommonElementsPage
(1).cs:line 81
   at
TestProject.SDK.Examples.Web.Test.RevalidationTests.RevalidationApplication2021HappyPathTestNurse.revalidationApplicationHappyPathTestNurse()
in C:\Users\ChrysanthiT\Desktop\NMC -
Copy\NMC_Online_Automation_Project\NMC_Online_Automation_Project\Web\Test\TestProject.SDK.Examples.Web.Test\Test\RevalidationTests\RevalidationTests\RevalidationApplication2021HappyPathTestNurse.cs:line
57

**Comment by basdijkstra** [comment]
Yes, that's a failing WebDriver command indeed. #121 improves the exception handling, by the way, but that's only available in the latest prerelease, not yet in an official release (it should be soon).

But would a solution like in my last comment be helpful here? As in: failing WebDriver commands are reported at all times, even when automatic driver command reporting is set to `false`?

**Comment by Chrys123** [comment]
Well how that would look like in the report though?

**Comment by basdijkstra** [comment]
There's a screenshot a few comments above this one: https://github.com/testproject-io/csharp-opensdk/issues/136#issuecomment-801821248

**Comment by Chrys123** [comment]
Oh so the driver command will be reported then?

Is there any way to replace the failed name with something else and not
show the driver command at the cover of the failed test?

**Comment by basdijkstra** [comment]
Yes, with the fix I implemented it will show failed driver commands even if `DisableCommandReports` is set to `true`.

I can replace the step name with something else, but I recommend keeping the driver command in there to quickly assess what went wrong. For example, when the driver command is `findElement`, I could make the error message look like this:

`Failed to execute command 'findElement'`

The screenshot and the message would remain unchanged.

**Comment by basdijkstra** [comment]
And FYI: we are probably going to make this a configurable feature in the next release. That means that you'll have three options:

1) Report no driver commands
2) Report only failing driver commands <-- this is what we're talking about right here in this issue
3) Report all driver commands

**Comment by Chrys123** [comment]
Yes thats fine, thank you

**Comment by basdijkstra** [comment]
That would make it look like this:

![image](https://user-images.githubusercontent.com/10740451/111638994-227b9e80-87fb-11eb-95b5-68fdf09596e5.png)

I'll check with someone else how to make this configurable, and I hope to add this feature in the next couple of days.

**Comment by Chrys123** [comment]
Yes thats great!

**Comment by basdijkstra** [comment]
I have just submitted #143, which adds the possibility to select reporting only the failed driver commands to the `DisableCommandReports` method. Please refer to the documentation for examples on how to use it.

Once this PR is merged, you can test it with the latest prerelease, or wait for the release of 0.65.2, which should be out soon.

**Comment by basdijkstra** [comment]
0.66.0 is released, please retest and close this issue when you feel it's resolved: https://www.nuget.org/packages/TestProject.OpenSDK/0.66.0

**Comment by Chrys123** [comment]
Sorry I was on holiday, so I am going to test it now

**Comment by Chrys123** [comment]
Im confused. Is reporter.step not working anymore?

**Comment by basdijkstra** [comment]
Which command is failing for you? Please include at least a code snippet because me having to guess what is wrong on your end is not productive..

`driver.Report().Step()` should still work fine.

**Comment by Chrys123** [comment]
well I have a  project where I do a global driver initialisation and i use
the reporter in my test classes.

I do webdriver.Report and it doesnt recognise it .

Can we please arrange a zoom call?

**Comment by basdijkstra** [comment]
@Rantzur1992 are you able to take a call with @Chrys123 ?

**Comment by Rantzur1992** [comment]
Hello @Chrys123 
Please send an email to ran.tzur@testproject.io
I will send you a zoom link.

**Comment by Rantzur1992** [comment]
@basdijkstra Just to make sure.

`reporter.DisableCommandReports(DriverCommandsFilter.All)`

It should report manual steps creation as well as catching and reports all possible errors that can be thrown while the test is executing?

**Comment by Chrys123** [comment]
As I saw the execution with Ran, it doesn't really bring up the screenshots
on the failed items and it reports also irrelevant errors like the close
driver (which shouldn't even be reported as why would there be an error??)

**Comment by basdijkstra** [comment]
> @basdijkstra Just to make sure.
> 
> `reporter.DisableCommandReports(DriverCommandsFilter.All)`
> 
> It should report manual steps creation as well as catching and report all possible errors that can be thrown while the test is executing?

That filters *all* driver commands, both passed and failed. It's all documented here: https://github.com/testproject-io/csharp-opensdk#disable-driver-command-reports

**Comment by Rantzur1992** [comment]
Right, so we need to pass DriverCommandsFilter.Pass to filter passed commands and keep only failed ones.

So right now, like me and @Chrys123 seen, screenshots are not uploaded (white screen).

This could be agent related.

**Comment by Chrys123** [comment]
Also, I am unable to generate reports

**Comment by Rantzur1992** [comment]
@Chrys123  If you are unable to generate the PDF report please reach out the Support chat, they will open a bug on this issue.

**Comment by Chrys123** [comment]
I am not able to generate only if the test has failures.

On passed tests I can

**Comment by Chrys123** [comment]
For me it's not working

**Comment by Rantzur1992** [comment]
Regarding the report generation, first please reach out to support@testproject.io so we will be able to investigate and open a bug on this if necessary.

Regarding the screenshots, when you run the test, in the moment it fails, do you see the browser window open and the web application is visible?

**Comment by Chrys123** [comment]
Yes it is perfectly visible.

**Comment by Rantzur1992** [comment]
Okay then, I am using an unreleased version of the SDK.
Let's wait until this version is released, and give it another try as I am unable to reproduce it on this version.

**Comment by Chrys123** [comment]
But I have version 0.66 as advised

**Comment by Rantzur1992** [comment]
@Chrys123 Correct but It's not the latest, there is also another one and an unreleased version.

Once the latest version is released, give it another try, it should work.
