### ISSUE TITLE
GenericDriver reports wrong inferred project name and job name for xUnit even when initialized in the same class

### ISSUE THREAD

**Issue by kishangupta-15** [testproject-io/csharp-opensdk#150]
Please refer the code and evidence mentioned in the issue #149. The project name is reported as System and the job name is reported as RuntimeTypeHandle. Expected project name is TestProjectSample and expected job name is GenericDriverTests.

**Comment by basdijkstra** [comment]
I'm not sure I can fix this. See #140 for more details. I'm happy to have another look, though.

**Comment by basdijkstra** [comment]
Making progress here, I've managed to get this working in *some* cases, but not yet in *all* cases.

**Comment by kishangupta-15** [comment]
@basdijkstra Thank you for a quick update!

**Comment by basdijkstra** [comment]
Looks like it works now. Solution is part of PR #153. Again, the result looks like this (`XUnit` is the final part of the namespace in my example, and `IssueTest` is the test class name):

![image](https://user-images.githubusercontent.com/10740451/112194884-a376d380-8c09-11eb-916f-5d0885c49f76.png)

Please retest with the latest prerelease after PR has been merged.

**Comment by basdijkstra** [comment]
PR #153 has been merged and released in https://www.nuget.org/packages/TestProject.OpenSDK/0.66.0.372-rc. Please retest and close this issue when you're happy with the result.

**Comment by kishangupta-15** [comment]
Retested the issue, its working fine now.

![image](https://user-images.githubusercontent.com/54025467/112507081-5be07b00-8db4-11eb-8262-c908e23473fd.png)
