### ISSUE TITLE
IWebElements are reported just by locators but element/locator names are missing

### ISSUE THREAD

**Issue by kishangupta-15** [testproject-io/csharp-opensdk#155]
Since the testproject reports would be shared with management and other non technical people as well, having just the locator/selectors like xpath, css etc doesn't help.

Expectation would be to see element/locator name plus locator. This should be a configurable for the user where user is able to select whether to see
1) just the element name
2) just the locator
3) or both element name and locator in the report.

![image](https://user-images.githubusercontent.com/54025467/112631518-feeccf80-8e5c-11eb-92e1-23b7245f4f3f.png)

**Comment by basdijkstra** [comment]
You know that the information is there, right? Just not in the step name, but it is in the details:

![image](https://user-images.githubusercontent.com/10740451/112637970-08673f00-8e3f-11eb-97d3-12126b76fb7c.png)

Anyway, this would require a change in the Agent first, before the SDKs can offer customization like this. @mstrelex what would be the best way for @kishangupta-15 to request a change like this?

**Comment by kishangupta-15** [comment]
@basdijkstra, @mstrelex - i meant element name that has been defined in the code, something like that has been mentioned here in 
https://github.com/testproject-io/java-opensdk/issues/59

For the below, i would expect the report to show me _firstViewBy, _firstEditBy, _firstHistoryBy as element names and locators as the defined XPath

![image](https://user-images.githubusercontent.com/54025467/112655316-43d13000-8e76-11eb-9ef2-4eb7a6a5f717.png)

**Comment by basdijkstra** [comment]
I don't see how that could ever work. Those are nothing but variable names, and those ‘disappear’ when you compile your code. The code that is run does not have access to those names.

The only way that this might work is by actively sending these variable names to the Agent, but that would require significant changes both in your test code and in the Agent, plus breaking / circumventing the WebDriver protocol because the call would be different.

An alternative would be to write wrapper methods yourself that submit a manual step with that information every time you execute a driver command and then disable the automatic driver command reporting. Happy to supply an example somewhere next week. Still, that would require a lot of refactoring in your test code..

**Comment by kishangupta-15** [comment]
Sure Bas, please do share an example, that would be great. I wonder how they are going to enhance this in Java OpenSDK, or maybe they won't.

**Comment by basdijkstra** [comment]
Sure, I'll try and do that somewhere next week.

The explanation above holds for Java and other SDKs, too.

**Comment by mstrelex** [comment]
Automatic reports use locators that are sent to the Selenium/Appium server.
Having your custom variable names or even when POM is used will require manual reporting.

**Comment by basdijkstra** [comment]
@kishangupta-15 you can find an example here: https://github.com/basdijkstra/testproject-opensdk-demo. I've disabled automatic command reporting and wrapped standard Selenium actions in `SeleniumHelpers` that take care of waiting and automatically report manual steps with their result to TestProject.

This is what the output looks like:

![image](https://user-images.githubusercontent.com/10740451/112999381-31554000-916f-11eb-839d-715287408a6a.png)

It might not be exactly what you want but you can play around with the exact messages as you see fit.

With this example, can we close this issue? As @mstrelex explained it's impossible to do this kind of reporting 'out of the box'.

**Comment by kishangupta-15** [comment]
@basdijkstra thank you for the example, I got what you guys are trying to say and I agree. Hence closing the issue from my side.

Btw I seen similar examples on your blog for plain Selenium WebDriver way back and already had implemented something very similar to that in one of my previous projects. Thanks a lot!
