### ISSUE TITLE
Improper binding of ports for C# openSDK

### ISSUE THREAD

**Issue by AnnaSwietek** [testproject-io/csharp-opensdk#156]
Improper binding of ports for C# openSDK occurs while starting the agent. The agent binds to local host addres, and later it operates on  port 8585.

It resembles the mechanism in vanilla appium, however in Vanilla Appium it is operational on all connected IP addresses, therefore all IP addresses are accessible.

While using an agent through a web browser it works correctly, problem occurs for agent used with openSDK for C#.

**Comment by basdijkstra** [comment]
I'm not sure that this is an issue specific to the C# OpenSDK, but rather how the Agent works. @mstrelex, do you have anything to add?

**Comment by mstrelex** [comment]
The agent binds to `localhost` on port **8585** only, for HTTPS it binds to all interfaces on port **8443** and is accessible via `https://local.rdr.tpagent.io`

@AnnaSwietek could you please elaborate on what is your scenario and how you use the SDK?

**Comment by AnnaSwietek** [comment]
Hi,

**Comment by Rantzur1992** [comment]
Thanks, @AnnaSwietek, this change will be implemented on the Agent side, which will then can be utilized from the SDK.
I will update you it is done.

**Comment by AnnaSwietek** [comment]
Hi Ran Tzur,

Could you let us know which openSDk will have the fix in place? 

Thank you & BR,
Anna

**Comment by Rantzur1992** [comment]
All SDKs will have it, since the implementation will be on the Agent side.

**Comment by Rantzur1992** [comment]
Hi @AnnaSwietek 
This has been implemented on boh the agent side and on the SDK
Please check this blog: https://blog.testproject.io/2021/04/28/distributed-execution-for-test-automation/
