### ISSUE TITLE
Documentation should mention the underlying version of selenium that OpenSDK is extending

### ISSUE THREAD

**Issue by kishangupta-15** [testproject-io/csharp-opensdk#167]
Documentation should mention the underlying version of selenium that OpenSDK is extending

**Comment by basdijkstra** [comment]
Can you give me a reason why, @kishangupta-15? You can always find this information in the `.csproj` file for the project:

https://github.com/testproject-io/csharp-opensdk/blob/9a024a7d83ef29ade0899999b94a337c601c6656/TestProject.OpenSDK/TestProject.OpenSDK.csproj#L29

**Comment by kishangupta-15** [comment]
Yes Bas, we can always find this information in .csproj file. But I believe that is the most important piece of information and it would be quite useful to add it in the documentation as opposed to checking .csproj file especially when presenting to management and non-technical actors.

**Comment by basdijkstra** [comment]
@Rantzur1992 what do you think?

**Comment by Rantzur1992** [comment]
@mstrelex I am sure it is possible?

**Comment by Rantzur1992** [comment]
@kishangupta-15 https://github.com/testproject-io/csharp-opensdk/pull/175
