### ISSUE TITLE
Apparently now code upload on Test Project cloud platform, does not support test fixtures

### ISSUE THREAD

**Issue by Chrys123** [testproject-io/csharp-opensdk#185]
I cannot run the tests online, because apparently I am using test fixtures. 

This needs to be resolved ASAP, as i need to be able to run tests in multiple browsers as well from the platform and use Nunit.

Please fix this ASAP

**Comment by Chrys123** [comment]
This was working before, I was using test fixtures in legacy SDK

**Comment by Chrys123** [comment]
Same issue is #181 but for Open SDK

**Comment by Rantzur1992** [comment]
Hello @Chrys123 
Uploading tests with Test Fixtures is not yet supported with the OpenSDK.

**Comment by Chrys123** [comment]
So when  is this going to be fixed please?
