### ISSUE TITLE
Can't install TestProject OpenSDK - Error: "Version conflict detected for xunit.assert"

### ISSUE THREAD

**Issue by gil-testproject** [testproject-io/csharp-opensdk#190]
When I try to install the OpenSDK, I get the following error:
![image](https://user-images.githubusercontent.com/81077108/117573212-4fec1680-b0df-11eb-9c06-0755137c20b3.png)

**Comment by Rantzur1992** [comment]
The SDK uses Xunit 2.4.1 which is the latest, updating your xunit version will solve the issue
