### ISSUE TITLE
Integration with Browser Stack

### ISSUE THREAD

**Issue by Chrys123** [testproject-io/csharp-opensdk#195]
Hi

So, since its going to be a while that you will implement the test fixtures, will integration with Browser Stack solve this problem temporarily for me to run the tests in multiple browsers?

**Comment by mstrelex** [comment]
@Chrys123 

Would you mind please sharing what was the behavior with legacy SDK and how the OpenSDK prevents it by not allowing the fixtures?

**Comment by Chrys123** [comment]
I have always been using the NUnit and the test fixtures library from NUnit to run my tests in multiple browsers. 

On Open Sdk, the tests cannot run from the platform as test fixtures are not supported.

I am asking here, if i integrate my tests with browser stack, will they run regardless? I want browser variety anyway

**Comment by s-glatshtein** [comment]
Hi Chrys. Can you please elaborate on how you were planning to parameterize the tests?

**Comment by Chrys123** [comment]
What do you mean?

I am using the test fixtures annotation from Nunit.

Then I call the base type inside my test class.

Can you please answer my question above?

Can Browser Stack integration allow me to run my coded tests?

**Comment by s-glatshtein** [comment]
You can run your tests on BrowserStack by setting the `cloud:URL` capability in the options root as follows:
```csharp
options.AddAdditionalCapability("cloud:URL", "YOUR_CLOUD_URL", true);
```

The reason i was asking was because you were talking about the issue you had with test fixtures.

**Comment by Chrys123** [comment]
It's not an issue I just have. It's an issue with Open SDK.

The platform doesn't support test fixtures as I've been told and therefore
I can't run my coded tests from there.

Therefore, I would need an alternative to run my tests in multiple browsers.

I have no clue how the integration with Browserstack works and the whole
thing is really confusing.

I am not just writing unit tests, I am writing full blown automation tests
with a large framework.

**Comment by Chrys123** [comment]
Can someone please give me a substantial answer on what I am asking here? 

It is really important please. I need to run the tests in multiple browsers, using NUnit and Test Fixtures on Browser Stack, without the platform in the middle.

Can someone answer if this can be done and how please?

**Comment by s-glatshtein** [comment]
I understand you need support for [TestFixure] annotation with parameters, and it may take some time until TestProject can upload & execute those correctly. In the meanwhile, if you would like to control the driver type from your tests, you can do one of the following:

1. Hard-code the driver type during upload. This is a temporary workaround only for uploads, until we are able to support your scenario.
2. Move the driver type parameter to each test method, and call the code that creates the driver from there - I understand this isn't a great solution, but it will allow you to reuse the same tests for multiple browsers

**Comment by Chrys123** [comment]
No its not please can you tell me if I can use Browser  stack with Test
Fixtures you are NOT answering my question here.

I am not going to change the whole structure of my code because of this.

I need to know please if I can run my tests in Browser stack with Test
fixtures

**Comment by s-glatshtein** [comment]
You cannot upload tests that use a [TestFixture] with parameters in it at this time, even with BrowserStack. We are still working on support for it.
In the meanwhile, you can return to legacy SDK until we add the support you need.

**Comment by Chrys123** [comment]
I cant do that, as  I have developed all my tests in the new Open SDK.
Nunit is a core runner for C# automation tests, I really do not understand why you do not have support in place for this.
Is it possible to give me a timeline as to when the support will take place?

Thanks

**Comment by Chrys123** [comment]
I have raised this issue with Browserstack separately now

**Comment by s-glatshtein** [comment]
Hi @Chrys123.
Since we were able to sort your issues with BrowserStack, and since proper integration was added to 1.2.1, i am now closing this issue.
