### ISSUE TITLE
When running a test on the dev environment, it doesnt show all the browsers

### ISSUE THREAD

**Issue by Chrys123** [testproject-io/csharp-opensdk#198]
It shows only Chrome in the reports section
![Browsers](https://user-images.githubusercontent.com/32673876/120618577-bd733480-c44a-11eb-88b6-791076d095c9.PNG)

**Comment by s-glatshtein** [comment]
Hi Chrys.
Can you check if by chance there is more than one report created? Is this the same test structure you were using in our previous conversations?

**Comment by Chrys123** [comment]
It's exactly the same structure, always use the latest version of SDK and
the agent

**Comment by s-glatshtein** [comment]
And is there always one report created or more? You can check the recent reports by hovering the _Report_ option in the platform

**Comment by Chrys123** [comment]
1 test run with 3 browsers = 1 report

**Comment by s-glatshtein** [comment]
Hi @Chrys123.
We think we fixed the problem. Can you please try again with the latest agent and see if it works now?

**Comment by Chrys123** [comment]
Its not working. Reopening

**Comment by s-glatshtein** [comment]
Hi Chrys. Can you please tell me what agent version you are using that reproduces the problem?

**Comment by Chrys123** [comment]
The latest one

**Comment by s-glatshtein** [comment]
Hi Chrys. I just ran the following scenario:

- Using the latest C# OpenSDK (i'm using 1.2.2)
- Using Agent 3.0.5
- Created a base class with 2 [TestFixture] annotations: 1 for chrome and 1 for firefox
- Created a test class with a single navigate step that inherits from the class above.
- Ran the test. Got 2 test cases, each ran on a different browser.
- Looked at the report and saw that it has 2 targets, each with 1 test containing 1 step.

Assuming you are using the same agent & SDK version, can you please describe how this is different to your scenario? I think i replicated your structure well and it seems to work fine

**Comment by Chrys123** [comment]
We can close this
