### ISSUE TITLE
Ghost Tests are being reported as skipped

### ISSUE THREAD

**Issue by kishangupta-15** [testproject-io/csharp-opensdk#199]
Ghost tests are being reported as skipped when executing tests.

![image](https://user-images.githubusercontent.com/54025467/122186331-8faad880-ceab-11eb-8c1b-40cac42e96ff.png)

I have only two tests, but as seen in the report above, 4 tests are being reported. Two of them are actual tests and two of them are ghost tests which are marked as skipped.

using Autofac;
using OpenQA.Selenium;
using Weiss.Configuration;
using Weiss.Panda.Testing.Website.Configuration;
using Weiss.Panda.Testing.Website.Driver;
using Xunit;
using Xunit.Abstractions;
using IWebDriver = TestProject.OpenSDK.Drivers.IWebDriver;

namespace Weiss.Panda.Testing.Website.Tests
{
    public class QuickTests : WebsiteTestBase
    {
        private readonly IConfigurationService _configurationService;
        private readonly IWebDriver _driver;

        public QuickTests(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
        {
            _configurationService = LifetimeScope.Resolve<IConfigurationService>();
            var driverConfiguration = _configurationService.GetSection<DriverConfiguration>();
            driverConfiguration.JobName = "QuickTests";
            _driver = LifetimeScope.Resolve<IWebDriver>(new NamedParameter("browser", BrowserType.Chrome),new NamedParameter("config", driverConfiguration));
        }

        [Fact]
        public void MyFirstTest()
        {
            _driver.Navigate().GoToUrl("http://example.testproject.io");
            _driver.FindElement(By.CssSelector("#name")).SendKeys("John Smith");
            _driver.FindElement(By.CssSelector("#password")).SendKeys("12345");
            _driver.FindElement(By.CssSelector("#login")).Click();
            //Assert.True(_driver.FindElement(By.CssSelector("#logout")).Displayed);
        }

        [Fact]
        public void MySecondTest()
        {
            _driver.Navigate().GoToUrl("http://example.testproject.io");
            _driver.FindElement(By.CssSelector("#name")).SendKeys("John Smith");
            _driver.FindElement(By.CssSelector("#password")).SendKeys("12345");
            _driver.FindElement(By.CssSelector("#login")).Click();
            //Assert.True(_driver.FindElement(By.CssSelector("#logout")).Displayed);
        }

        public override void Dispose()
        {
            base.Dispose();
            _driver.Quit();
        }
    }
}

**Comment by s-glatshtein** [comment]
Thank you for submitting this issue. Can you attach your base class as well for reference?

**Comment by kishangupta-15** [comment]
Sure.

using Autofac;
using Weiss.Ioc.Extensions;
using Weiss.Testing;
using Xunit.Abstractions;

namespace Weiss.Panda.Testing.Website
{
    public abstract class WebsiteTestBase : TestBase
    {
        private static readonly IContainer _container;
        protected readonly ILifetimeScope LifetimeScope = _container.BeginLifetimeScope();

        static WebsiteTestBase()
        {
            var containerBuilder = new ContainerBuilder();
            containerBuilder.RegisterWeissModules();
            _container = containerBuilder.Build();
        }

        protected WebsiteTestBase(ITestOutputHelper testOutputHelper = null) :
            base(testOutputHelper)
        { }

        public override void Dispose()
        {
            LifetimeScope?.Dispose();
        }
    }
}






using System.Linq;
using Autofac;
using TestProject.OpenSDK.Drivers;
using TestProject.OpenSDK.Drivers.Generic;
using Weiss.Configuration;
using Weiss.Panda.Testing.Website.Configuration;
using Weiss.Panda.Testing.Website.Driver;
using Xunit.Abstractions;
using Xunit.Sdk;

namespace Weiss.Panda.Testing.Website
{
    public class WebsiteIocModule : Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            base.Load(builder);

            //xUnit TestOutputHelper
            builder.Register(context => new TestOutputHelper())
                .As<ITestOutputHelper>()
                .InstancePerLifetimeScope();

            //Configuration Service
            builder.RegisterType<ConfigurationService>()
                .As<IConfigurationService>()
                .InstancePerLifetimeScope();

            //IWebDriver
            builder.Register((x, y) =>
                {
                    var parameters = y.ToList();
                    return new DriverFactory().GetDriver<IWebDriver>(parameters.Named<BrowserType>("browser"),
                            parameters.Named<DriverConfiguration>("config"));
                })
                .As<IWebDriver>()
                .InstancePerLifetimeScope();

            /*//GenericDriver
            builder.Register(x => new DriverFactory().GetDriver<GenericDriver>(BrowserType.Generic))
                .As<GenericDriver>()
                .InstancePerLifetimeScope();*/
        }
    }
}

**Comment by kishangupta-15** [comment]
@SantoshYakkala, @s-glatshtein Not the same issue

**Comment by SantoshYakkala** [comment]
> > @s-glatshtein Even I have reported the same issue during our catchup today. I am able to fix this issue by removing two things in our code base.
> > 
> > 1. Multiple Driver instantiations
> > 2. IDisposable interface in class inheritance
> > 
> > namespace My_Test.Runner
> > {
> > public class DriverBase **: IDisposable //Removed this IDisposable interface**
> > {
> > **public IWebDriver driver { get; set; } // Removed this line of code and used Webdriver Manager driver instantiation**
> > ```
> >     public DriverBase()
> >     {
> >         driver = WebDriverManager.GetInstanceOfWebDriverManager().GetDriver(Config.Browser);
> >         driver.Navigate().GoToUrl(Config.TalosUrl);
> >         driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromMinutes(Config.DriverTimeoutInMins);
> >     }
> >     public void Dispose()
> >     {
> >         WebDriverManager.GetInstanceOfWebDriverManager().CloseDriver();
> >         driver.Dispose();
> >     }
> >     private void GotoUrl()
> >     {
> >         driver.Navigate().GoToUrl(Config.Url);
> >     }
> >   
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > After modifying the code. I did not see Skipped in our TestProject reports.
> > @kishangupta-15 Can you also please check your code
> 
> @SantoshYakkala, @s-glatshtein Not the same issue

@kishangupta-15 , Can you please provide your TestBase class as well

**Comment by s-glatshtein** [comment]
Hi @kishangupta-15. Wanted to let you know that we found the source of the problem. It should be fixed in the next release

**Comment by kishangupta-15** [comment]
> Hi @kishangupta-15. Wanted to let you know that we found the source of the problem. It should be fixed in the next release

@s-glatshtein Thank you for the update

**Comment by s-glatshtein** [comment]
Hi @kishangupta-15 . I believe your issue was fixed in the newest agent. Can you please try it and let me know if it works?

**Comment by kishangupta-15** [comment]
@s-glatshtein I have checked with Agent v 3.0.5 and this issue doesn't exist anymore. Thank you for resolving this.
