### ISSUE TITLE
Either blank test name or incorrect test name is getting reported

### ISSUE THREAD

**Issue by kishangupta-15** [testproject-io/csharp-opensdk#217]
![image](https://user-images.githubusercontent.com/54025467/123983016-282f7580-d9e1-11eb-9c17-9ede93528253.png)

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using TestProject.OpenSDK.Drivers.Generic;
using System.Threading.Tasks;
using HtmlAgilityPack;
using TestProject.OpenSDK.Drivers;
using TestProject.OpenSDK.Drivers.Web;
using TestProject.OpenSDK.Internal.CallStackAnalysis;
using Xunit;

namespace TestProjectSample
{
    public class GenericDriverTests : IDisposable
    {
        private readonly HttpClientHandler _httpClientHandler;
        private readonly HttpClient _httpClient;
        private readonly IWebDriver _driver;
        private readonly Uri _baseUrl;

        public DriverTests()
        {
            string url;
            //url = "https://example.testproject.io/web/";
            url = "https://www.google.com/";

            _httpClientHandler = new HttpClientHandler { UseDefaultCredentials = true };
            _httpClient = new HttpClient(_httpClientHandler);
            _driver = new ChromeDriver(projectName:"DevProject");
            _baseUrl = new Uri(url);
        }

        [Fact]
        public async Task GenericDriverTest()
        {
            string projectName = StackTraceHelper.Instance.GetInferredProjectName();
            string jobName = StackTraceHelper.Instance.GetInferredJobName();
            string methodName = StackTraceHelper.Instance.GetInferredTestName();

            /*_driver.Report().Step("Step 1", "First Step");
            _driver.Report().Step("Step 2", "Second Step");
            _driver.Report().Step("Starting Tests");*/
            //_driver.Report().Step("Step 3");

            var initialWebsiteUrls = await GetInitialWebsiteUrls();

            

            var tasks = initialWebsiteUrls
                .Take(10)
                .Select(async url =>
                {
                    try
                    {
                        //_driver.Report().Step("Step 4");
                        var statusCode = await GetStatusCodeForUrl(url);
                        //_driver.Report().Step("Step 5");

                        return new
                        {
                            Url = url,
                            StatusCode = statusCode
                        };
                    }
                    catch (Exception ex)
                    {
                        //_driver.Report().Step("Step 6");
                        throw new Exception($"Error requesting status code for url [{url}]: {ex.Message}", ex);
                    }

                }).ToList();

            //_driver.Report().Step("Step 7");
            await Task.WhenAll(tasks);
            _driver.Report().Step("Step 8");
            string testName = StackTraceHelper.Instance.GetInferredTestName();

            _driver.Report().Step($"Status code for url as Something", "Passed", true);
            var errors = new StringBuilder();
            _driver.Report().Step("Step 9");
            foreach (var task in tasks)
            {
                if (task.IsFaulted)
                {
                    errors.AppendLine($"Error: {task.Exception?.Message}");
                }

                if (task.Result.StatusCode != HttpStatusCode.OK)
                {
                    errors.AppendLine($"Status code for url [{task.Result.Url}] as [{task.Result.StatusCode}]");
                }
            }

            Assert.True(errors.Length == 0, errors.ToString());
            _driver.Report().Step("Ending Tests");
        }

        private async Task<HttpStatusCode> GetStatusCodeForUrl(Uri url)
        {
            var response = await _httpClient.GetAsync(url);
            return response.StatusCode;
        }

        private async Task<ICollection<Uri>> GetInitialWebsiteUrls()
        {
            var results = new List<Uri>();
            var response = await _httpClient.GetAsync(_baseUrl);

            if (response.StatusCode != HttpStatusCode.OK)
            {
                Assert.True(false, $"Unable to determine initial website urls from [{_baseUrl}].");
            }

            var htmlDocument = new HtmlDocument();
            htmlDocument.LoadHtml(await response.Content.ReadAsStringAsync());

            foreach (var node in htmlDocument.DocumentNode.SelectNodes("//a[@href]"))
            {
                var hrefValue = node.GetAttributeValue("href", null);
                if (!string.IsNullOrWhiteSpace(hrefValue))
                {
                    var url = GetAbsoluteUrl(_baseUrl, hrefValue);
                    if (url != null)
                    {
                        results.Add(url);
                    }
                }
            }

            return results
                .Distinct()
                .ToList();
        }

        private Uri GetAbsoluteUrl(Uri baseUrl, string absoluteOrRelativeUrl)
        {
            if (Uri.TryCreate(absoluteOrRelativeUrl, UriKind.Absolute, out Uri result1))
            {
                return result1;
            }

            if (Uri.TryCreate(baseUrl, absoluteOrRelativeUrl, out Uri result2))
            {
                return result2;
            }

            //OutputHelper.WriteLine($"Unable to determine absolute url for [{absoluteOrRelativeUrl}]");
            return null;
        }

        public void Dispose()
        {
            _httpClient?.Dispose();
            _httpClientHandler?.Dispose();
            _driver.Quit();
        }
    }
}

If any step is manually reported before "var initialWebsiteUrls = await GetInitialWebsiteUrls();", then we get the correct test name. However, if steps are reported after that step, then the test name in the report is reported as blank.

Case 1: At least a single Step is reported before "var initialWebsiteUrls = await GetInitialWebsiteUrls();"
StackTraceHelper.Instance.GetInferredTestName(); => This returns correct test name, if executed before above code
currentTestName is set in the reporter instance which is used to report the subsequent steps after the above code
StackTraceHelper.Instance.GetInferredTestName(); => This returns blank, if executed after above code

Case 2: No Step is reported before "var initialWebsiteUrls = await GetInitialWebsiteUrls();"
StackTraceHelper.Instance.GetInferredTestName(); => This returns correct test name, if executed before above code
currentTestName doesn't gets initialized
StackTraceHelper.Instance.GetInferredTestName(); => This returns blank, if executed after above code so subsequent steps are reported with blank name after the above code

This issue exists for both GenericDriver and ChromeDriver. Maybe present with other drivers as well, I haven't checked it with other drivers

Please refer #149 and #150 issues which are related to this.

**Comment by s-glatshtein** [comment]
Hi @kishangupta-15. You mentioned reporting steps before and after the initial website urls task. Are those step reports happening inside the `ContinuteWith` calls you have? Does it happen if all your `Report().Step` calls are from the test and not inside any tasks?

**Comment by kishangupta-15** [comment]
@s-glatshtein We don't have ContinueWith calls in our code. If a step is reported before initial website url tasks, then all the further steps are reported with the correct test name. I think the GetInitialWebsiteUrls() function rests the call stack due to which blank test name gets generated.

I had some related issues #149 and #150 to this, which were resolved earlier, maybe these can help.

**Comment by s-glatshtein** [comment]
Thanks for the extra information @kishangupta-15. I've ran a little investigation of my own:

- Wrote a simple test
- Ran the entire test code with `Task.Run(...).Wait()` - saw the empty test name phenomenon.
- Ran 1 driver command before - Got the correct test name
- Ran 1 driver command after - Got the correct test name

Is this consistent with the behavior you're seeing?

**Comment by kishangupta-15** [comment]
@s-glatshtein Yes Shai, this is consistent with what the behavior that I saw. If there is no driver command that is ran before the Task.Run(...).Wait(), the driver command after also give blank test name.

**Comment by s-glatshtein** [comment]
Hi @kishangupta-15.
I ran some checks and it is impossible to infer the test name if the command runs inside another task. This is because the test name inferring relies on the current stack trace, and running a test in a task executes it in a separate thread with no trace (get it?) of the original test method.
Right now i don't see a way this scenario can be supported by automatic reporting. You shouldn't use automatic test name inferring for your case.

**Comment by kishangupta-15** [comment]
@s-glatshtein
Thank you for the update. I understand that nothing can be done regarding this as of now. Hence closing the issue.
