### ISSUE TITLE
DriverBuilder is unable to create a new instance of ChromeDriver and throws exception

### ISSUE THREAD

**Issue by kishangupta-15** [testproject-io/csharp-opensdk#218]
DriverBuilder throws exception {"Failed to create an instance of TestProject.OpenSDK.Drivers.Web.ChromeDriver"} and is thus unable to create a new instance of ChromeDriver.

using System;
using OpenQA.Selenium;
using TestProject.OpenSDK.Drivers;
using Xunit;
using Xunit.Abstractions;
using ChromeDriver = TestProject.OpenSDK.Drivers.Web.ChromeDriver;

namespace TestProjectSample
{
    public class DriverBuilder
    {
        private readonly ITestOutputHelper _testOutputHelper;

        public DriverBuilder(ITestOutputHelper testOutputHelper)
        {
            _testOutputHelper = testOutputHelper;
        }

        [Fact]
        public void DriverBuilderTest()
        {
            ChromeDriver driver = null;
            try
            {
                driver = new DriverBuilder<ChromeDriver>()
                    .WithProjectName("DevProject")
                    .WithJobName("DriverBuilder")
                    .Build();

                /*driver = new ChromeDriver(
                    disableReports: false
                    , projectName: "DevProject"
                    , jobName: "DriverBuilder");*/
            }
            catch (Exception ex)
            {
                _testOutputHelper.WriteLine(ex.Message);
            }

            if (driver != null)
            {
                driver.Navigate().GoToUrl("https://example.testproject.io");
                driver.FindElement(By.CssSelector("#name")).SendKeys("John Smith");
                driver.FindElement(By.CssSelector("#password")).SendKeys("12345");
                driver.FindElement(By.CssSelector("#login")).Click();
                Assert.True(driver.FindElement(By.CssSelector("#greetings")).Displayed);

                driver.Quit();
            }
        }
    }
}

**Comment by mstrelex** [comment]
@kishangupta-15 

This is indeed a regression since 1.2.0, it will be fixed in the next release.

**Comment by mstrelex** [comment]
@kishangupta-15 

This is fixed in https://github.com/testproject-io/csharp-opensdk/releases/tag/v1.2.2

**Comment by kishangupta-15** [comment]
@mstrelex I have verified this issue and it is working as expected. Thank you for resolving this.
