### ISSUE TITLE
Provided token for 'Development' session is invalid!

### ISSUE THREAD

**Issue by SantoshYakkala** [testproject-io/csharp-opensdk#219]
Provided token for 'Development' session is invalid! message is displayed when running C# code on OpenSDK version 1.2.1.

Note: Downgrade to OpenSDK v1.2.0 worked without any issue.

This is the message displayed in the agent log file.

2021-07-05 22:51:14.931 DahlR2G_hE2jzfTS2VJ-eQ  ERROR 29268 idle-entry      i.t.a.b.a.d                              GET https://api.testproject.io/api/v1/agent/tokens?type=Development&token=*** - 403 (sb3xGBBq): Token was not found
2021-07-05 22:51:14.932 DahlR2G_hE2jzfTS2VJ-eQ  INFO  29268 idle-entry      i.t.a.b.b.c                              Token Development is invalid
2021-07-05 22:51:15.153 DahlR2G_hE2jzfTS2VJ-eQ  ERROR 29268 idle-entry      i.t.a.b.a.d                              GET https://api.testproject.io/api/v1/agent/tokens?type=Development&token=*** - 403 (2zWUvS0o): Token was not found
2021-07-05 22:51:15.153 DahlR2G_hE2jzfTS2VJ-eQ  INFO  29268 idle-entry      i.t.a.b.b.c                              Token Development is invalid
2021-07-05 22:51:15.767 DahlR2G_hE2jzfTS2VJ-eQ  ERROR 29268 idle-entry      i.t.a.b.a.d                              GET https://api.testproject.io/api/v1/agent/tokens?type=Development&token=*** - 403 (bnWtZHsK): Token was not found
2021-07-05 22:51:15.768 DahlR2G_hE2jzfTS2VJ-eQ  INFO  29268 idle-entry      i.t.a.b.b.c                              Token Development is invalid

**Comment by mstrelex** [comment]
Hi @SantoshYakkala 

Starting from version 1.2.1, 
when a token is provided in both the constructor and an environment variable, 
the token in the environment variable will be used.

Can you please check if you have one defined?

Also please check the console logs of your IDE,
Do you see a message `Using TP_DEV_TOKEN parameter from environment` ?

**Comment by SantoshYakkala** [comment]
Hi @mstrelex,

I am using environment variable for the token and the same value is being passed to the chromedriver.

**Comment by mstrelex** [comment]
@SantoshYakkala 

I can't reproduce this locally. 
The only thing that has changed for you is the SDK version?
The asterisks `***` in your post are your valid token?

**Comment by kishangupta-15** [comment]
@SantoshYakkala @mstrelex 
I think you are using DriverBuilder for creating your driver instance. If have already logged the same issue 6 days ago. Please refer #218 
The issue is with DriverBuilder. If you use new ChromeDriver() to initiate your driver, you won't face this issue.

**Comment by SantoshYakkala** [comment]
> @SantoshYakkala @mstrelex
> I think you are using DriverBuilder for creating your driver instance. If have already logged the same issue 6 days ago. Please refer #218
> The issue is with DriverBuilder. If you use new ChromeDriver() to initiate your driver, you won't face this issue.

@kishangupta-15 I am not using DriverBuilder. Passing the token information directly to ChromeDriver.

**Comment by mstrelex** [comment]
@kishangupta-15 This is not related to #218 as this is not an exception in building the driver but something that has to do with how the token is passed.

**Comment by mstrelex** [comment]
@SantoshYakkala Can you print it in console with enclosing brackets something like `[ABC123]` to make sure it is indeed the correct token and has no invisible characters?

**Comment by SantoshYakkala** [comment]
@mstrelex Found out the root cause of the issue.
Here are the steps to repo the issue.

1. Login to your TestProject Account->Integration->SDK
2. Get your developer token
3. Set the developer token in the environment variable TP_DEV_TOKEN
4. Start the agent
5. Run your test from your visual studio

**Expected Result:** Tests Should run successfully

**Actual Result:** Tests are getting successfully executed

6. Navigate to TestProject Account->Integration->SDK
7. Refresh/create the developer token
8. Update the developer token in the environment variable TP_DEV_TOKEN
9. Restart or Quit/ Start the agent immediately
10. When you debug the code your code will have the latest token, but your agent will still have the old token

**Issue fix:** Agent need to be Quit for minimum of 1 minute and Start the agent after 1 minute to reflect the changes

**Comment by s-glatshtein** [comment]
Hi Santosh.
Just to clarify, is the TP_DEV_TOKEN environment variable updated in your system settings, or in your visual studio's .runsettings file? If it is the former, then you need to restart visual studio for the environment variable's value to refresh. Environment variables are fixed when a process starts, so changing them in your OS will not change them in any running processes.

**Comment by SantoshYakkala** [comment]
> Hi Santosh.
> Just to clarify, is the TP_DEV_TOKEN environment variable updated in your system settings, or in your visual studio's .runsettings file? If it is the former, then you need to restart visual studio for the environment variable's value to refresh. Environment variables are fixed when a process starts, so changing them in your OS will not change them in any running processes.

Hi Shai,

TP_DEV_TOKEN is updated in the system environment variables and I am reading the TP_DEV_TOKEN value from environment variable using this "private static string DevToken = Environment.GetEnvironmentVariable("TP_DEV_TOKEN", EnvironmentVariableTarget.Machine);"

**Comment by s-glatshtein** [comment]
Thanks for the clarification Santosh.
This is how the OpenSDK chooses what dev token to use, as for 1.2.1:

1. Check the current process environment for TP_DEV_TOKEN - this is updated from parent process when it starts, meaning if you update the environment variable, you will need to restart you Visual Studio afterwards.
2. If no environment variable is present, check the `token` property that is sent to the driver.
3. If niether is present, raise an error that no token was provided

In your case, i believe that you refreshed the dev token but did not restart visual studio/command line. That means it used the old environment, since windows doesn't update the variables of already-running processes.
Hope this clarifies my previous comments

**Comment by SantoshYakkala** [comment]
Thanks for providing the information, but this wasn't the behavior in v1.2.0. In v1.2.0 it works as expected without closing the Visual Studio.

**Comment by kishangupta-15** [comment]
> Thanks for the clarification Santosh.
> This is how the OpenSDK chooses what dev token to use, as for 1.2.1:
> 
> 1. Check the current process environment for TP_DEV_TOKEN - this is updated from parent process when it starts, meaning if you update the environment variable, you will need to restart you Visual Studio afterwards.
> 2. If no environment variable is present, check the `token` property that is sent to the driver.
> 3. If niether is present, raise an error that no token was provided
> 
> In your case, i believe that you refreshed the dev token but did not restart visual studio/command line. That means it used the old environment, since windows doesn't update the variables of already-running processes.
> Hope this clarifies my previous comments

@mstrelex @s-glatshtein 

As per the current dev token selection process, TestProject OpenSDK is giving priority to the environment variable over the token sent to driver i.e. higher level is getting priority(environment) over lower level(passed token).
But usually the priority is given to lower level and then the higher level variable. So, is there are specific reason why we are giving priority to higher level environment variable here in our case?

I had one more question which is not relevant to this. It is that we don't have a driver builder for Generic Driver. Is this also by design?

**Comment by SantoshYakkala** [comment]
@s-glatshtein Thanks for the information provided.. This is an functionality change and behavior is as expected.. Closing the issue.

**Comment by s-glatshtein** [comment]
Hi @kishangupta-15. I will open an issue to add the missing driver builders

**Comment by kishangupta-15** [comment]
@s-glatshtein Thank you Shai!
And could you also clarify my doubt about the precedence of TP_DEV_TOKEN variable?
