### ISSUE TITLE
Reports performance with latency issues - allow reporting steps at batches from OpenSDK 

### ISSUE THREAD

**Issue by oriddd** [testproject-io/csharp-opensdk#228]
Due to performance issues, with latency issues.
Current logic is reporting steps one by one.
Additional logic is required to fix that performance issues with latency issues.
Instead of reporting steps one by one - report steps at batches of up to 10 steps in a time.

**Comment by s-glatshtein** [comment]
The related PR was merged and therefore the issue can be closed.
