### ISSUE TITLE
WebDriverWait with ExpectedCondition InvisibilityOfElementLocated results in failed step being reported even when it return true output

### ISSUE THREAD

**Issue by kishangupta-15** [testproject-io/csharp-opensdk#232]
Driver = new ChromeDriver();
 wait = new WebDriverWait(Driver, TimeSpan.FromSeconds(10));
wait.Until(ExpectedConditions.InvisibilityOfElementLocated(locator);

Output should be: Any ExpectedConditions which return a boolean value should only be reported as failure when it returns false.

![image](https://user-images.githubusercontent.com/54025467/125605055-641422ed-4570-43e0-bcb5-e8b4350d0a9e.png)

**Comment by s-glatshtein** [comment]
Thanks for reporting this issue. We will take a look at it and update you when a fix is available
