### ISSUE TITLE
ChromeOptions are not being passed to the driver correctly and hence ChromeBrower is not being set up as required

### ISSUE THREAD

**Issue by kishangupta-15** [testproject-io/csharp-opensdk#233]
var chromeOptions = new ChromeOptions();
chromeOptions.AddUserProfilePreference("download.default_directory", FolderManager.DownloadsPath);
chromeOptions.AddUserProfilePreference("intl.accept_languages", "nl");
chromeOptions.AddUserProfilePreference("disable-popup-blocking", "true");
IWebDriver driver = new ChromeDriver(chromeOptions:chromeOptions, disableReports:true);
driver.Navigate().GoToUrl("https://stackoverflow.com/questions/33434443/download-file-at-custom-path-using-selenium-webdriver");

If we use the above code using TestProject driver, the default download path of the browser doesn't change.
On the other hand, if we use Selenium Driver instead of TestProject driver, this works as expected and the default download path along with other passed attributes are passed to the driver instance.

**Comment by s-glatshtein** [comment]
Thanks for reporting this issue.
I believe a fix will be available in the upcoming agent release. We will keep you posted when it is released.

**Comment by s-glatshtein** [comment]
Hi @kishangupta-15. We just released a new agent version. Can you try it and see if the capabilities work for you now?

**Comment by s-glatshtein** [comment]
Hi @kishangupta-15. Were you able to try the new agent and see if the issue was resolved?

**Comment by kishangupta-15** [comment]
@s-glatshtein - Thank you for the fix. I have tested it and it is working as expected. Closing the issue.
