### ISSUE TITLE
iOS performance drop

### ISSUE THREAD

**Issue by AnnaSwietek** [testproject-io/csharp-opensdk#240]
for iOS HTML test execution there is a significant drop of performance (not only for our automation tool integration, but also for the script used with openSDK)

- for our automation tool integration the time went up from 01:32.1 to 06:42.8 min
- for the script used with openSDK the time went up from 00:10 to 00:55.5 min

**Comment by mstrelex** [comment]
@AnnaSwietek 

iOS HTML is the automation of websites in mobile Safari?
Can you send a code snippet and Agent logs to us?

**Comment by AnnaSwietek** [comment]
The highest performance drops are at session start, and once you chooce a vale from combobox, then it locks up for a few minutes. 
Session initiation for us lasts 1.5 minutes, with TP 7 minutes.
Choosing combobox with us 7 sec, with TP 4 min 7 sec - choosing the country in combobox
Web session setup 4 min 40 sec, ours 30 sec
