### ISSUE TITLE
SpecFlow Plugin doesn't target .NET Framework 4.6.1

### ISSUE THREAD

**Issue by SabotageAndi** [testproject-io/csharp-opensdk#71]
Runtime plugins have to target .NET Framework 4.6.1 and .NET Standard 2.0. 

Docs: https://docs.specflow.org/projects/specflow/en/latest/Extend/Plugins.html#runtime-plugins

.NET 4.6.1 does support "theoretical" .NET Standard 2.0, but we had problems with it (e.g. assembly load errors for netstandard.dll), and so we are targeting the runtime of SpecFlow for .NET 4.6.1 and .NET Standard 2.0. And that's why runtime plugins target also additionally .NET 4.6.1.

**Comment by basdijkstra** [comment]
Hey @SabotageAndi, we did target .NET Framework 4.6.1 originally, but wouldn't that effectively make the plugin a Windows-only plugin? We run our CI on Linux machines and including .NET Framework 4.6.1 gave build errors, too, that's why we removed it.

@vitalybu, anything to add here?

**Comment by SabotageAndi** [comment]
When you multitarget the project (produce .NET 4.6.1 assemblies and .NET Standard 2.0 assemblies) this is no problem. MSBuild picks depending on the project where the NuGet package is used, the correct assembly.

About building it on Linux. You probably need the reference assemblies.

``` XML
<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.0">
   <PrivateAssets>all</PrivateAssets>
   <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
```

In SpecFlow we have it in our Directory.Build.props file: https://github.com/SpecFlowOSS/SpecFlow/blob/master/Directory.Build.props#L14

With this, it should be able to build .NET 4.6.1 on Linux.

**Comment by basdijkstra** [comment]
Thanks!

I'll add those soon and see what happens in CI.

**Comment by basdijkstra** [comment]
I've just submitted #73, which adds .NET 4.6.1 as a target framework for the SpecFlow plugin.

**Comment by basdijkstra** [comment]
Since #73 has been merged, could you have another look and close this issue when you think it’s OK now, @SabotageAndi ?

**Comment by SabotageAndi** [comment]
Sorry @basdijkstra, but I forgot one .NET Core SDK behavior.
Since .NET Core 3.0 everything from the NuGet packages is copied to the output directory.
But this does not happen for .NET Core 2.1. In that case, only the NuGet package reference is not enough.

We solved this in SpecFlow and SpecFlow+ with some custom MSBuild props/targets in the NuGet package.
I made the needed changes in my fork at https://github.com/SabotageAndi/csharp-sdk/commit/04b6438f0868244ad04faddf72057c17de30aa1b

But this copies only the Plugin-dll, not the `TestProject.OpenSDK.dll`. And here I stopped because fixing this would need to add the same stuff to the general `TestProject.OpenSDK` package. I didn't want to do this, before we are talking about the issue.

Dependencies in plugins of SpecFlow are always a hassle.

**Comment by basdijkstra** [comment]
Thanks. I’ll try and have a look at that tomorrow, or otherwise I’ll address it on Monday.

**Comment by basdijkstra** [comment]
@SabotageAndi I'm happy to also add this to the C# SDK as well as the plugin, but I'm not entirely sure what risks we're running if we don't do this? I'm sort of new to this, so some more explanation would be very beneficial. Thanks!

**Comment by basdijkstra** [comment]
@SabotageAndi is this still relevant? If so I'll diver deeper into this.

**Comment by basdijkstra** [comment]
@SabotageAndi I'm closing this issue for now, as I haven't heard any troubles related to it from customer support or our users. If these do come up, I'm happy to have the issue reopened and apply the changes you suggested.

**Comment by SabotageAndi** [comment]
Fine for me!
