### ISSUE TITLE
TestTracer API change with SpecFlow 3.6

### ISSUE THREAD

**Issue by SabotageAndi** [testproject-io/csharp-opensdk#74]
I noticed that you are inherit from `TestTracer`. With SpecFlow 3.6, which will be released probably on Monday, we are changing the interface. This will break your plugin.

Also I think there are better ways to integrate into SpecFlow. In 3.5 we added the [RuntimePluginTestExecutionLifecycleEvents](https://github.com/SpecFlowOSS/SpecFlow/blob/master/TechTalk.SpecFlow/Plugins/RuntimePluginTestExecutionLifecycleEvents.cs). This gives you access via a plugin to the same runtime events like hooks.

There you can access the `ScenarioContext` and `ScenarioStepContext` via DI to get the data you need.

This would also remove the need for https://github.com/testproject-io/csharp-sdk/blob/main/TestProject.OpenSDK.SpecFlowPlugin/TestProjectStepContext.cs. The static properties on this class will make problems, when the tests are executed in parallel.

**Comment by basdijkstra** [comment]
Hmm.. That sounds like a rework of the plugin is a good idea. I won’t do that before Wednesday, though, since it works with SpecFlow 3.5 as of now and I don’t want to use untested code in a webinar.

I’ll make this high priority after that, it doesn’t sound like it is a very complicated operation now that I know how writing a plugin actually works..

**Comment by SabotageAndi** [comment]
Then please limit the NuGet package to SpecFlow 3.5. We will have 3.6 out on Monday and with the breaking change, it will not work for the users. They will get probably some MethodNotFoundExceptions.

**Comment by basdijkstra** [comment]
Currently, SpecFlow itself is not actually a dependency of the plugin. Do you recommend adding it as a dependency? I think that's the only way in which we can put hard restrictions on the SpecFlow version.

We're currently discussing if and how we will keep supporting the current plugin, redesigning it so it can be used with SpecFlow 3.6 is a top priority.

**Comment by SabotageAndi** [comment]
About which dependency are we talking?

You have it in the csproj: https://github.com/testproject-io/csharp-sdk/blob/main/TestProject.OpenSDK.SpecFlowPlugin/TestProject.OpenSDK.SpecFlowPlugin.csproj#L29
and in the NuGet package https://www.nuget.org/packages/TestProject.OpenSDK.SpecFlowPlugin/0.0.0.247-rc

![image](https://user-images.githubusercontent.com/859801/105482408-9f314700-5ca8-11eb-8325-83cd3b3dc5f6.png)

**Comment by basdijkstra** [comment]
Today is not my day :S Thanks. Just submitted #75 which restricts the plugin (in its current implementation) from being used together with SpecFlow 3.6.

As soon as the new plugin is ready, well simply support anything from SpecFlow 3.5.5 upwards.

**Comment by basdijkstra** [comment]
Hey @SabotageAndi, I could use a little help here... I've sent you a couple of messages on the SpecFlow Discord channel, too. Thanks!

**Comment by SabotageAndi** [comment]
@basdijkstra I just saw them. I am in a call until 3 and will answer you then. Ok?

**Comment by basdijkstra** [comment]
Thanks :)

**Comment by basdijkstra** [comment]
I've just submitted #76, which contains the new implementation of the SpecFlow plugin that should be compatible with SpecFlow 3.6. Thanks again, @SabotageAndi, for the quick answers to my questions.

**Comment by basdijkstra** [comment]
@SabotageAndi what should we do to close this issue? Do you want to test it for yourself using SpecFlow 3.6? Should I do it once again and show you the results? I'd like to get this one off the list.

**Comment by SabotageAndi** [comment]
I wasn't aware that you are waiting on me to close the issue.
