### ISSUE TITLE
Test name not always reported when driver.Quit() isn't called

### ISSUE THREAD

**Issue by s-glatshtein** [testproject-io/csharp-opensdk#77]
I ran this code sample:
```csharp
using System.Threading;
using NUnit.Framework;
using TestProject.OpenSDK.Drivers.Web;

namespace OpenSDKCleanExample
{
    public class Tests
    {
        private ChromeDriver driver;
        
        [SetUp]
        public void Setup()
        {
            driver = new ChromeDriver();
        }

        [Test]
        public void MyFirstTest()
        {
            driver.Navigate().GoToUrl("http://example.testproject.io");
            driver.FindElementByCssSelector("#name").SendKeys("John Smith");
            driver.FindElementByCssSelector("#password").SendKeys("12345");
            driver.FindElementByCssSelector("#login").Click();
        }
    }
}
```

After running it, I expected to see `MyFirstTest` as test name in the reports, but instead it was `Test`.
I don't think it happens every time, but happened quite often.
**NOTE:** all the driver commands are always reported correctly (at least on my machine) so there is that :)

**Comment by basdijkstra** [comment]
This line should take care of that, but obviously it doesn't work as well as it should..

https://github.com/testproject-io/csharp-sdk/blob/322acafbfe55960d44746fee3802802143360e87/TestProject.OpenSDK/Drivers/BaseDriver.cs#L90

I'll have a closer look.

**Comment by s-glatshtein** [comment]
I took a closer look at the logs, and it looks like the socket is disconnected before the test name is reported. Maybe there's a race condition between the two, which causes the problem?
I had a similar issue in java-sdk. Here's the issue link: https://github.com/testproject-io/java-sdk/issues/69

**Comment by basdijkstra** [comment]
Hey @s-glatshtein, can this one be closed now that #84 is merged?

**Comment by s-glatshtein** [comment]
sure thing!

**Comment by basdijkstra** [comment]
Excellent. Closing.
