### ISSUE TITLE
Improve test name inferring for testing platforms

### ISSUE THREAD

**Issue by s-glatshtein** [testproject-io/csharp-opensdk#78]
Given the following NUnit test method:
```csharp
[Test(Description = "My first test")]
[Description("My first test description")]
public void MyFirstTest()
{
// Test Code...
}
```

My expectation would be that test name would be inferred as `My first test`, but instead the reports show `MyFirstTest` (the method name).
I get the same behavior when using Xunit test with the following attribute:
```csharp
[Fact(DisplayName = "My first test")]
```
And MSTest when using the following attribute:
```csharp
[TestMethod("My first test")]
```

**Comment by basdijkstra** [comment]
You're right, these are not yet detected by the inferrer mechanisms. Labeling this as an enhancement, shouldn't be too difficult to implement.

**Comment by basdijkstra** [comment]
Hey @s-glatshtein, can this one be closed now that #80 is merged?

**Comment by s-glatshtein** [comment]
sure!

**Comment by basdijkstra** [comment]
Excellent. Closing.
