### ISSUE TITLE
[Readme] Readme issues

### ISSUE THREAD

**Issue by gileli121** [testproject-io/csharp-opensdk#87]
Hi, I found readme issue here:

![image](https://user-images.githubusercontent.com/17680514/106379791-15276380-63b7-11eb-9518-49fd59d5711f.png)

I found that this is the way that it can be compiled
```c#
using TestProject.OpenSDK.Drivers.Web;
using ChromeOptions = OpenQA.Selenium.Chrome.ChromeOptions; // Must add this. Otherwise it will fail to compile
....
....

ChromeDriver driver = new ChromeDriver(chromeOptions: new ChromeOptions());
```

@basdijkstra 
I prefer if you create tag called `readme` so I will able to open multiple readme issues instead of opening it in one issue as I have been told.  Otherwise, I will edit this message over time or post message here (but I don't like to work like this)

**Comment by basdijkstra** [comment]
Just submitted #93 which fixes some bugs and inconsistencies in the README. Feel free to have a look if you want, @gileli121:

https://github.com/testproject-io/csharp-opensdk/blob/fix/issue_87_readme/README.md

**Comment by gileli121** [comment]
@basdijkstra 
I can't see the link.
Getting 404

**Comment by basdijkstra** [comment]
I see, that's because the PR has been merged already. Here you go:

https://github.com/testproject-io/csharp-opensdk/blob/main/README.md

**Comment by gileli121** [comment]
Great,
Another thing, Do we support data driven in NUnit, MSTest and XUnit?
I did not found information about it in the readme.

If we don't support it, I think that we should specify it under new section called "Limitation"

**Comment by basdijkstra** [comment]
This issue has been inactive for over two weeks now, so I'm closing it. Feel free to reopen it if you feel something still needs to be addressed.
