### ISSUE TITLE
Generated reports on xunit contain wrong test details - OpenSDK [SDK 0.65.1]

### ISSUE THREAD

**Issue by dorbenzvi** [testproject-io/csharp-opensdk#91]
Generated reports while using xunit is not inferring the correct project name, job name, and test name.
Code:

`using System;
using Xunit;

namespace XUnitTestProject1
{
    using OpenQA.Selenium;
    using TestProject.OpenSDK.Drivers.Web;

 
    public class UnitTest1
    {
        private ChromeDriver driver;
        [Fact]
        public void StartBrowser()
        {
            this.driver = new ChromeDriver(token: "token_here");
            this.driver.Navigate().GoToUrl("https://example.testproject.io");
            this.driver.FindElement(By.CssSelector("#name")).SendKeys("John Smith");
            this.driver.FindElement(By.CssSelector("#password")).SendKeys("12345");
            this.driver.FindElement(By.CssSelector("#login")).Click();
            this.driver.Quit();
        }
      
       
    }
}
`

Report:
![image](https://user-images.githubusercontent.com/55704483/106445469-bbdb3500-6487-11eb-865a-fc818f82e4c1.png)

**Comment by basdijkstra** [comment]
I've just submitted #94, which addresses the broken project, job and test name inferring logic for xUnit.NET. I've also added some unit tests to hopefully prevent these issues from turning up again in the future..

**Comment by basdijkstra** [comment]
Did you find some time to retest this yet with the latest prerelease, @dorbenzvi? I'd like to close the issue if it has been addressed properly.

**Comment by dorbenzvi** [comment]
> Did you find some time to retest this yet with the latest prerelease, @dorbenzvi? I'd like to close the issue if it has been addressed properly.

Hi @basdijkstra 
Yes, it's working now.

**Comment by basdijkstra** [comment]
Excellent. Closing this issue.
