### ISSUE TITLE
NUnit - Disabled tests not reported

### ISSUE THREAD

**Issue by gileli121** [testproject-io/csharp-opensdk#96]
Not sure if it is bug or maybe it is improvement.
Anyway, I checked how the SDK works with disabled tests that have for example `[Ignore("Disabled for a reason")]`

This is the code I wrote:
```c#
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.Text;
using TestProject.OpenSDK.Drivers.Web;

namespace NUnitTests
{
    class NUnitFeatures
    {
        ChromeDriver driver;

        [SetUp]
        public void SetupTest()
        {
            driver = new ChromeDriver();
        }

        [Test]
        [Ignore("Disabled for a reason")]
        public void Simple_Test_That_Disabled()
        {
            driver.Navigate().GoToUrl("https://testproject.io/");
        }

        [Test]
        public void Simple_Test_That_Not_Disabled()
        {
            driver.Navigate().GoToUrl("https://google.com/");
        }


        [TearDown]
        public void AfterEachTest()
        {
            driver.Quit();
        }
    }
}
```

In this case, the disabled test will not reported and you will see only the regular test that not disabled

![image](https://user-images.githubusercontent.com/17680514/106733324-6e430180-661a-11eb-8b3d-87358155d795.png)

**Comment by basdijkstra** [comment]
Of course this test will not be reported. The test will not be executed in the first place (that's what the `@Ignore` annotation does), so no driver session will be created and no report will be sent to TestProject.

I don't see this as a bug, nor do I think anything should be improved here, it works exactly as I expected.

**Comment by basdijkstra** [comment]
Hey @gileli121, because it has been almost a week with no further comments or questions related to this issue, I'm closing it for now. Feel free to reopen it if you feel something needs to be done about the situation you describe.
