### ISSUE TITLE
I want to convert my automation Tests from SDK V1 to Open SDK

### ISSUE THREAD

**Issue by Chrys123** [testproject-io/csharp-opensdk#98]
I need to use the Test Fixtures from NUnit for multiple browsers, but before there was a runner that I could do that, now there isnt.

I would need to accommodate multiple browsers on my local environment and also convert my project structure to Open SDK as seamlessly as possible.

I am using the Page object model and I also would like to do global driver initialisation for all my tests, something that i find hard to do now.

Is it possible to post a small project example with the above requests?

Thanks

**Comment by basdijkstra** [comment]
@s-glatshtein since you're the expert on the SDK v1, could you help @Chrys123 out here? I'm happy to provide some examples using page objects for the OpenSDK for different browsers, although most of those can be found in the examples already:

https://github.com/testproject-io/csharp-opensdk/tree/main/TestProject.OpenSDK.Tests/Examples

**Comment by Chrys123** [comment]
I would need to accomodate multiple browser execution from my frameworkk,

**Comment by basdijkstra** [comment]
I am sure there are plenty of examples on how to do that with Selenium to be found online. Since all we do with the SDK is extend the existing Selenium browsers, the only thing you'd need to change is import the driver class (`ChromeDriver`, etc.) from the SDK rather than from Selenium itself.

**Comment by basdijkstra** [comment]
Closing.

**Comment by Chrys123** [comment]
hmm im  sorry but testproject directed me here.

It's hard to use the fixtures here without the common runner that existed in previous SDK

**Comment by basdijkstra** [comment]
@Chrys123 could you give me a code example of your current test setup then? An example or two of test classes (i.e., classes annotated with `[TestFixture]`) will do. I'll see what I can do for you.

**Comment by Chrys123** [comment]
using NUnit.Framework;
using TestProject.Common.Enums;
using TestProject.SDK.Examples.Web.Test.Base;

namespace TestProject.SDK.Examples.Web.Runners.Nunit
{   
	[TestFixture(AutomatedBrowserType.Chrome)]
	[TestFixture(AutomatedBrowserType.Edge)]
    
	public class RevalidationTests : TestBase
	{   
		Runner runner;
    
		public RevalidationTests(AutomatedBrowserType automatedBrowserType){
			runner = new RunnerBuilder(DevToken).WithDriverCommandReportingDisabled().AsWeb(automatedBrowserType).Build();
		}

        [Ignore("fjmvjgv")]
		[Test, Order(1)]
		public void RunRevalidationLogin2021NurseTest(){  
		  RunRevalidationLogin2021NurseTest(runner);
		}

        [Ignore("fjmvjgv")]
		[Test, Order(2)]
		public void RunRevalidationLogin2021MidwifeTest(){  
		  RunRevalidationLogin2021MidwifeTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(3)]
		public void RunRevalidationLogin2021NurseAndMidwifeTest(){  
		  RunRevalidationLogin2021NurseAndMidwifeTest(runner);
		}

		[Ignore("fjmvjgv")]
		[Test, Order(4)]
		public void RunRevalidationLogin2021NurseAndSCPHNTest(){  
		  RunRevalidationLogin2021NurseAndSCPHNTest(runner);
		}
		
		[Ignore("fjmvjgv")]
		[Test, Order(5)]
		public void RunRevalidationApplication2021HappyPathTestNurse(){  
		   RunRevalidationApplication2021HappyPathTestNurse(runner);
		}

        [Ignore("fjmvjgv")]
		[Test, Order(6)]
		public void RunRevalidationApplication2021AnnualDirectDebitSetup(){  
		   RunRevalidationApplication2021AnnualDirectDebitSetup(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(7)]
		public void RunRevalidationApplication2021QuarterlyDirectDebitSetup(){  
		   RunRevalidationApplication2021QuarterlyDirectDebitSetup(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(8)]
		public void RunRevalidationApplication2021PayByCardTest(){  
		   RunRevalidationApplication2021PayByCardTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(9)]
		public void RunRevalidationExtensionRequest2021HappyPathNurseTest(){  
		   RunRevalidationExtensionRequest2021HappyPathNurseTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(10)]
		public void RunRegistrationLapseNurse2021Test(){  
		   RunRegistrationLapseNurse2021Test(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(11)]
		public void RunRevalidationApplication2021NoCurrentPracticeTest(){  
		   RunRevalidationApplication2021NoCurrentPracticeTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(12)]
		public void RunRevalidationApplication2021PractiseOutsideUKTest(){  
		   RunRevalidationApplication2021PractiseOutsideUKTest(runner);
		}

        [Ignore("fjmvjgv")]
		[Test, Order(13)]
		public void RunRevalidationApplication2021NoRequiredHoursTest(){  
		   RunRevalidationApplication2021NoRequiredHoursTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(14)]
		public void RunRevalidationApplication2021ManagedHealthConditionTest(){  
		   RunRevalidationApplication2021ManagedHealthConditionTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(15)]
		public void RunRevalidationApplication2021NotManagedHealthConditionTest(){  
		   RunRevalidationApplication2021NotManagedHealthConditionTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(16)]
		public void RunRevalidationApplication2021NoGoodCharacterTest(){  
		   RunRevalidationApplication2021NoGoodCharacterTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(17)]
		public void RunRevalidationApplication2021CriminalConvictionTest(){  
		   RunRevalidationApplication2021CriminalConvictionTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(18)]
		public void RunRevalidationApplication2021RegulatoryBodyFindingTest(){  
		   RunRevalidationApplication2021RegulatoryBodyFindingTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(19)]
		public void RunRevalidationApplication2021NoInsuranceTest(){  
		   RunRevalidationApplication2021NoInsuranceTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(20)]
		public void RunRevalidationApplication2021HighRiskAuditTest(){  
		   RunRevalidationApplication2021HighRiskAuditTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(21)]
		public void RunRevalidationApplication2021MediumRiskAuditTestNoRegularAppraisals(){  
		   RunRevalidationApplication2021MediumRiskAuditTestNoRegularAppraisals(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(22)]
		public void RunRevalidationApplication2021MediumRiskAuditTestNoNMCRegisteredLineManager(){  
		   RunRevalidationApplication2021MediumRiskAuditTestNoNMCRegisteredLineManager(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(23)]
		public void RunRevalidationApplication2021HappyPathTestNurseAndSCPHN(){  
		   RunRevalidationApplication2021HappyPathTestNurseAndSCPHN(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(24)]
		public void RunRevalidationApplication2021HappyPathTestNurseAndMidwife(){  
		   RunRevalidationApplication2021HappyPathTestNurseAndMidwife(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(25)]
		public void RunRevalidationApplication2021LapseNurseLapseMidwifeTest(){  
		   RunRevalidationApplication2021LapseNurseLapseMidwifeTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(26)]
		public void RunRegistrationLapseNurseScphn2021Test(){  
		   RunRegistrationLapseNurseScphn2021Test(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(27)]
		public void RunRevalidationApplication2021RevalidateNurseLapseMidwifeTest(){  
		   RunRevalidationApplication2021RevalidateNurseLapseMidwifeTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(28)]
		public void RunRevalidationApplication2021RevalidateNurseLapseSCPHNTest(){  
		   RunRevalidationApplication2021RevalidateNurseLapseSCPHNTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(29)]
		public void RunRegistrationLapseMidwife2021Test(){  
		   RunRegistrationLapseMidwife2021Test(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(30)]
		public void RunRevalidationApplication2021HappyPathTestMidwife(){  
		   RunRevalidationApplication2021HappyPathTestMidwife(runner);
		}
		
		[Ignore("fjmvjgv")]
		[Test, Order(31)]
		public void RunRevalidationApplication2021AnnualDirectDebitSetupOnExpiryDateTest(){  
		   RunRevalidationApplication2021AnnualDirectDebitSetupOnExpiryDateTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(32)]
		public void RunRevalidationApplication2021QuarterlyDirectDebitSetupOnExpiryDateTest(){  
		   RunRevalidationApplication2021QuarterlyDirectDebitSetupOnExpiryDateTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(33)]
		public void RunRevalidationExtensionRequest2021HappyPathMidwifeTest(){  
		   RunRevalidationExtensionRequest2021HappyPathMidwifeTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(34)]
		public void RunRevalidationExtensionRequest2021HappyPathNurseAndMidwifeTest(){  
		   RunRevalidationExtensionRequest2021HappyPathNurseAndMidwifeTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(35)]
		public void RunRevalidationExtensionRequest2021HappyPathNurseAndSCPHNTest(){  
		   RunRevalidationExtensionRequest2021HappyPathNurseAndSCPHNTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(36)]
		public void RunRevalidationExtensionRequest2021MoreThanOneExtensionReasonTest(){  
		   RunRevalidationExtensionRequest2021MoreThanOneExtensionReasonTest(runner);
		}
        
		[Ignore("fjmvjgv")]
		[Test, Order(37)]
		public void RunRevalidationApplication2021NoContactableManagerTest(){  
		   RunRevalidationApplication2021NoContactableManagerTest(runner);
		}
		
		[Test, Order(38)]
		public void RunCheckRevalidationApplicationDataNurseDynamics(){  
		   RunCheckRevalidationApplicationDataNurseDynamics(runner);
		}
   
	    [OneTimeTearDown]
		public void TearDown(){  
			runner.Dispose();
        }
    }
}

**Comment by basdijkstra** [comment]
How about something like this?

```csharp
namespace TestProject.OpenSDK.Tests.Examples.Frameworks.NUnit
{
    using global::NUnit.Framework;
    using OpenQA.Selenium;
    using TestProject.OpenSDK.Drivers.Web;
    using TestProject.OpenSDK.Internal.Helpers.DriverOptions;

    [TestFixture(BrowserType.Chrome)]
    [TestFixture(BrowserType.Firefox)]
    public class MultipleBrowserTest
    {
        private IWebDriver driver;
        private BrowserType browserType;

        public MultipleBrowserTest(BrowserType type)
        {
            this.browserType = type;
        }

        [SetUp]
        public void StartBrowser()
        {
            switch (this.browserType)
            {
                case BrowserType.Chrome:
                    this.driver = new ChromeDriver();
                    break;
                case BrowserType.Firefox:
                    this.driver = new FirefoxDriver();
                    break;
                default:
                    throw new System.Exception("Unsupported browser type");
            }
        }

        public void ExampleTestUsingChromeDriver()
        {
            this.driver.Navigate().GoToUrl("https://example.testproject.io");
            this.driver.FindElement(By.CssSelector("#name")).SendKeys("John Smith");
            this.driver.FindElement(By.CssSelector("#password")).SendKeys("12345");
            this.driver.FindElement(By.CssSelector("#login")).Click();

            Assert.IsTrue(this.driver.FindElement(By.CssSelector("#greetings")).Displayed);
        }
```
The `BrowserType` enum can be found in the `TestProject.OpenSDK.Internal.Helpers.DriverOptions` namespace. I would recommend you creating an enum of your own, though, that contains all the browser type your test supports.

**Comment by Chrys123** [comment]
Thanks for the help. Is there any open sdk documentation that gives me the interfaces and the libraries?

**Comment by basdijkstra** [comment]
Other than the documentation provided in the code and the examples in the README.md, no, at least not yet. You could always clone the repository and generate that documentation yourself using a tool of your preference, though.

**Comment by basdijkstra** [comment]
@Chrys123 please let me know if there's anything else I can do to help on this subject. If not, please feel free to close the issue. Thanks.
