### ISSUE TITLE
Why did you delete my question about the multiple browser setup????

### ISSUE THREAD

**Issue by Chrys123** [testproject-io/csharp-opensdk#99]
I had asked for an example about multiple browser setup and you deleted it

**Comment by basdijkstra** [comment]
The example I gave you is still there: https://github.com/testproject-io/csharp-opensdk/issues/98. It has just moved to the closed issues because you closed the issue.

**Comment by Chrys123** [comment]
I cant see it unless i have the specific link.

I will close this
